# Sample TOML configuration file for freebee
#
# freebee searches first for ./.freebee.toml and then
# for $HOME/.freebee.toml. It reads the first one it
# finds and then stops.

[floppy]
	disk = "/path/to/floppy.img"	# Floppy disk is optional

[hard_disk]
	disk1 = "/path/to/hd.img"
	disk2 = "/path/to/hd2.img"	# Second disk is optional

[display]
	x_scale = 1.0			# Scale in X dimension, 0 < n <= 45
	y_scale = 1.0			# Scale in Y dimension, 0 < n <= 45
	red = 0x00			# foreground colors
	green = 0xFF
	blue = 0x00

[roms]
	rom_14c = "/path/to/roms/14c.bin"	# Odd locations
	rom_15c = "/path/to/roms/15c.bin"	# Even locations

[serial]
	symlink = "serial-pty"
